sudo: false
language: ruby
cache: bundler
rvm:
  - ruby-head
  - jruby-head
  - 2.0.0
  - 2.1.8
  - 2.2.4
  - 2.3.0
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
before_install:
  - gem update --system
  - gem install bundler
  - gem --version
notifications:
  email: false
